name: Feature Suggestion
description: Suggest an feature for Minehut
title: "[Feature Request]: "
labels: ["feature request"]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Confirm all of these are checked and valid.
      options:
        - label: I have read and agree to the README (found on https://github.com/Minehut/Meta)
          required: true
        - label: I am NOT reporting a security vulnerability
          required: true
        - label: I have searched the Issue Tracker to make sure this is not a duplicate issue
          required: true
        - label: This issue does not contain any sensitive information
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Where are you?
      multiple: true
      options:
        - Java
        - Bedrock
        - Website
        - Discord
        - Other
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What is your fantastic, super incredible, must have idea?
      description: What feature are you suggesting? Include a clear and concise description of the feature 
      render: shell
    validations:
      required: true
  - type: textarea
    id: howuse
    attributes:
      label: How can people use it to do amazing things?
      description: Who does the feature benefit? How is it useful to people?
      render: shell
    validations:
      required: true
  
