name: Filter Request
title: "[FILTER]: "
labels: filter request
description: Suggest a filter edit
body:
  - type: markdown
    attributes:
      value: |
        Minehut filter request guide

        Fill out the template. Don't write inside the arrows as they will be hidden
        when you post your issue.

        If you have a filter request for Minehut, read the following:

        1.  Fill out the template
             It makes it a lot easier for everyone when issues conform to the standard templates. It also ensures we have the necessary information. To fill a checkbox, put an "x" in between the [ ] like: [x]

        2. Keep the issue title the same as the default provided. Please do not include the filtered phrase in the issue title. 
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Confirm all of these are checked and valid.
      options:
        - label: I have read and agree to the README (found on https://github.com/Minehut/Meta)
          required: true
        - label: I have ensured the phrase is not properly filtered on the platform
  - type: dropdown
    id: platform
    attributes:
      label: Which filter has the issue?
      multiple: true
      options:
        - Discord
        - Minecraft
    validations:
      required: true
  - type: dropdown
    id: filter
    attributes:
      label: Should the phrase be filtered or unfiltered?
      options:
        - Filter
        - UnFilter
    validations:
      required: true
  - type: textarea
    id: phrase
    attributes:
      label: Phrase
      description: Whats the phrase?
      render: shell
    validations:
      required: true
  
