name: Filter Request
title: "[FILTER]: "
labels: filter request
description: Report an issue with the filter
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Confirm all of these are checked and valid.
      options:
        - label: I have read and agree to the README (found on https://github.com/Minehut/Meta)
          required: true
        - label: I have ensured the phrase is not properly filtered on the platform
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Which filter has the issue?
      multiple: true
      options:
        - Discord
        - Minecraft
    validations:
      required: true
  - type: dropdown
    id: filter
    attributes:
      label: Should the phrase be filtered or unfiltered?
      options:
        - Filter
        - UnFilter
    validations:
      required: true
  - type: textarea
    id: phrase
    attributes:
      label: Phrase
      description: What phrase was filtered?
      render: shell
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why should we do this?
      render: shell
    validations:
      required: false
  
